---
- name: create a list from dictionary
  hosts: localhost
  gather_facts: false
  vars:
    users:
      name: mohie
      shells:
        - /bin/bash
        - /bin/sh
      role: admin
      path: /home/mohie

  

  tasks:
    

    - name: test dict2items filter
      set_fact:
          my_list: "{{users | dict2items(key_name='keyx', value_name='valuex')}}"
      tags:
        - always

    - name: debug
      debug:
        msg: "{{looping}}"
      loop: "{{my_list}}"
      loop_control:
        loop_var: looping
      tags:
        - never


