---
- name: create a list from dictionary
  hosts: localhost
  gather_facts: false
  vars:
    users:
      name: mohie
      shell: /bin/bash
      role: admin
      path: /home/mohie

  

  tasks:
    

    - name: test dict2items filter
      set_fact:
          my_list: "{{users | dict2items(key_name='keyx', value_name='valuex')}}"


    - name: debug
      debug:
        msg: "{{my_list}}"
      tags:
        - d2i

    - name: turn it back to dictionary
      debug:
        msg: "{{my_list | items2dict(key_name='keyx', value_name='valuex')}}"
      tags:
        - i2d
