---
- name: network interfaces
  hosts: all
  gather_facts: true
  tasks:

    - name: deploy template
      template:
        src: filters.j2
        dest: /tmp/filter.txt
        force: true
      delegate_to: localhost
      run_once: true
    
    - name: lookup and filter
      debug:
        msg: "{{item  | ipaddr('net')}}"
      loop: "{{lookup('file', '/tmp/filter.txt').splitlines()}}"
