---
- name: play with find
  hosts: localhost
  vars:
    - find_path: /etc
  tasks:


    - name: find some files
      find:
        paths: "{{find_path}}"
        use_regex: false
        file_type: file
        patterns: ['*.conf', '*.config']
        recurse: true
      register: findOut
      tags:
        - always


    - name: get a list of paths for files owned by root
      debug:
        msg: "{{findOut['files'] | selectattr('pw_name', 'eq', 'root') | map(attribute='path')}}"


    - name: store a list of paths for files owned by root and manipulate the header
      set_fact:
        root_owned_list: "{{findOut['files'] | selectattr('pw_name', 'eq', 'root') | map(attribute='path') | map('regex_replace', '^(.*)$', 'root_owned: \\1')}}"
    
    - name: put list in a file somewhere
      template:
        src: root_owned.j2
        dest: /tmp/root_owned.txt
        force: true
