---
- name: first template
  hosts: all
  vars:
    - external_variabl: 'from_the_playbook'
  tasks:

    - name: print some variables
      debug:
        msg: 
          - "{{ansible_user}}"
          - "{{inventory_hostname}}"
          - "{{external_variable}}"
